import type { Metadata } from "next";
import { Sahitya } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Sahitya({ subsets: ["devanagari"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex-grow md:flex  px-6">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
